pool:
  vmImage: 'macos-latest'
  demands: xcode

steps:
- task: UseDotNet@2
  displayName: 'Install .NET sdk'
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: CmdLine@2
  displayName: 'Install Maui Workload'
  inputs:
    script: 'dotnet workload install maui'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'CAS-Dev.p12'
    certPwd: 'p12_Password'
    keychain: 'temp'

