# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'macos-latest'
  demands: xcode

- task: UseDotNet@2
  displayName: 'Install DotNet'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: CmdLine@2
  inputs:
    script: 'dotnet workload install maui'


