pool:
  vmImage: 'macos-latest'
  demands: xcode

steps:
- task: UseDotNet@2
  displayName: 'Use .NET sdk'
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: CmdLine@2
  inputs:
    script: 'dotnet workload install maui'

