pool:
  name: Azure Pipelines
  demands: xcode

steps:
- script: |
    curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.x
    dotnet --info
  displayName: 'Command Line Install .NET'

- script: 'dotnet workload install maui'
  displayName: 'Command Line - Install MAUI workload'
